before_script:
  - docker info

build_image:
  # stage: build
  script:
    - docker build . -t flaskblog
    - if [ $(docker ps -aq --filter name= flaskblog) ]; then docker rm -f flaskblog;fi
    - docker run -itd -p 5000:5000 --name flaskblog flaskblog
  only:
    # 只在主分支执行此任务
    - main

# deploy:
#   stage: deploy
#   script:
#     - docker run -it --rm -p 5000:5000 flaskblog
#   only:
#     - main
